//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoCaps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoCaps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4r5e
        ///5h1t
        ///5hit
        ///a55
        ///anal
        ///anus
        ///ar5e
        ///arrse
        ///arse
        ///ass
        ///ass-fucker
        ///asses
        ///assfucker
        ///assfukka
        ///asshole
        ///assholes
        ///asswhole
        ///a_s_s
        ///b!tch
        ///b00bs
        ///b17ch
        ///b1tch
        ///ballbag
        ///balls
        ///ballsack
        ///bastard
        ///beastial
        ///beastiality
        ///bellend
        ///bestial
        ///bestiality
        ///bi+ch
        ///biatch
        ///bitch
        ///bitcher
        ///bitchers
        ///bitches
        ///bitchin
        ///bitching
        ///bloody
        ///blow job
        ///blowjob
        ///blowjobs
        ///boiolas
        ///bollock
        ///bollok
        ///boner
        ///boob
        ///boobs
        ///booobs
        ///boooobs
        ///booooobs
        ///booooooobs
        ///breasts
        ///buceta
        ///bugger
        ///bum
        ///bunny fucker
        ///butt
        ///butthole
        ///buttmuch
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string profanity {
            get {
                return ResourceManager.GetString("profanity", resourceCulture);
            }
        }
    }
}
