#DO NOT REMOVE THIS LINE - MiNET Config
#ip=0.0.0.0
port=19132

ForceXBLAuthentication=false
UseEncryption=false
UseEncryptionForAll=false
ForceOrderingForAll=false
EnableQuery=false

MinWorkerThreads=4000
MinCompletionPortThreads=1000

MaxNumberOfPlayers=800

CalculateLights=false
CalculateSkyLights=false
MoveRenderDistance=1
ViewDistance=32
MaxViewDistance=32
PluginDirectory=/home/kenny/Documents/Github/OpenMiNET/WorldGenerator/src/WorldGenerator.Tweaking/bin/Debug/net10.0/
#PluginDirectory=Plugins

CommandsEnabled=true

#   OpenAPI Config
EnableThroughput=false
EnableOpenServerInfo=false

#   Interval in seconds to output the serverinfo at.
InfoInterval=1000

LevelDBWorldFolder=cityyy
PCWorldFolder=/home/kenny/Downloads/KingsLanding1

#   You can disable plugins as follows:
Plugin.RandomBreakBlocker.Enabled=false
Plugin.MetricsPlugin.Enabled=false
Plugin.PickaxeDebug.Enabled=false

Plugin.OpenAPI.TestPlugin.Enabled=false
Plugin.CrossReferencing.Enabled=false
Plugin.ChatFilter.Enabled=false
Plugin.ExplodingArrows.Enabled=true

Plugin.ManagementApiPlugin.Enabled=false

Plugin.OpenApi.GameEngine.Enabled=false
Plugin.TNTRun.Enabled=true

Save.Interval=300
Save.Enabled=false

GameMode=Creative

Plugin.Multiverse.Enabled=false
Plugin.WorldGeneratorPlugin.Enabled=true

WorldGen.IsDefault=true
WorldGen.Debug=truesadsz